apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: frendyol-microservice
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  selector:
    app: gateway
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: frendyol-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - image: aspq/frendyolgateway
          name: gateway
          ports:
            - containerPort: 80
          env:
            - name: SPRING_PRODUCT_URL
              value: http://product-service:8080/api/v1/products
            - name: SPRING_ORDER_URL
              value: http://order-service:8081/api/v1/orders
            - name: SPRING_USER_URL
              value: http://user-service:8082/api/v1/user