apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: frendyol-microservice
spec:
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
  selector:
    app: order-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: frendyol-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - image: aspq/order_service
          name: order-service
          ports:
            - containerPort: 8081
          env:
            - name: PRODUCT_SERVICE_URL
              value: http://product-service:8080/api/v1/products
            - name: MONGODB_URL 
              value: mongodb://mongo-db:27017/orders
            - name: USER_SERVICE_URL
              value: http://user-service:8080/api/v1/user