apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: frendyol-microservice
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: product-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: frendyol-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - image: aspq/product_service
          name: product-service
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_URL
              value: mongodb://mongo-db:27017/products